swagger: "2.0"
info:
  title: Tests API
  version: ~
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /buckets/{bucketKey}/tests:
    get:
      summary: Returns a list of tests.
      description: ""
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
    post:
      summary: Create a test.
      description: ""
      operationId: ""
      parameters:
      - in: body
        name: NewTest
        schema:
          $ref: '#/definitions/holder'
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
  /buckets/{bucketKey}/tests/{testId}:
    delete:
      summary: Delete a single test.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
  /buckets/{bucketKey}/tests/{testId}/environments:
    get:
      summary: Return details of the test's environments (only those that belong to
        the specified test)
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: bucketKey
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
    post:
      summary: Create new test environment.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: bucketKey
      - in: body
        name: NewEnvironment
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
  /buckets/{bucketKey}/tests/{testId}/environments/{environmentId}:
    put:
      summary: Update the details of a test environment.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: bucketKey
      - in: path
        name: environmentId
        description: Unique identifier for a test environment
      - in: body
        name: ModifiedEnvironment
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
  /buckets/{bucketKey}/tests/{testId}/steps:
    get:
      summary: List test steps for a test.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
    post:
      summary: Add new test step.
      description: ""
      operationId: ""
      parameters:
      - in: body
        name: NewStep
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
  /buckets/{bucketKey}/tests/{testId}/steps/{stepId}:
    delete:
      summary: Delete a step from a test.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: stepId
        description: Unique identifier for a step
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
    put:
      summary: Update the details of a single test step.
      description: ""
      operationId: ""
      parameters:
      - in: body
        name: NewStep
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: testId
        description: Unique identifier for a test
      responses:
        200:
          description: OK
      tags:
      - ""
      security: []
definitions: []