swagger: "2.0"
info:
  title: Users API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  '/users ':
    ' get ':
      summary: Users
      description: Returns all customers users.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Users
    ' post ':
      summary: Users
      description: Creates a new user.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Users
    ' put ':
      summary: Users
      description: Updates a user.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Users
  '/users/{user_guid} ':
    ' delete ':
      summary: Users {user_guid}
      description: Deletes a user.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Users
    ' get ':
      summary: Users {user_guid}
      description: Returns customers user by user GUID.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Users
definitions: []