swagger: "2.0"
info:
  title: Roles API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  '/roles ':
    ' get ':
      summary: Roles
      description: ttttReturn user rolesttt
      operationId: -roles-
      responses:
        200:
          description: OK
      tags:
      - ""
definitions: []